services:
  fingram-bot:
    build: .
    container_name: fingram_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data           # Хранение БД
      - ./config:/app/config       # Проброс конфигов
    env_file:
      - config/.env
    extra_hosts:
      - "host.docker.internal:host-gateway" # Разрешаем доступ к хосту из контейнера

  # Опционально: можно запускать Ollama внутри композа
  # ollama:
  #   image: ollama/ollama:latest
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   ports:
  #     - "11434:11434"

  # Опционально: можно запустить PostgresSQL базу данных
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres_container
  #   environment:
  #     POSTGRES_USER: postgres_user
  #     POSTGRES_PASSWORD: postgres_password
  #     POSTGRES_DB: postgres_db
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   ports:
  #     - "5430:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
  ollama_data:
